# Generated by Django 5.1.15 on 2026-06-27 14:38

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('cost_foreign', apps.common.models.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Себестоимость (валюта)')),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='Валюта')),
                ('cost_kzt', apps.common.models.MoneyField(decimal_places=2, max_digits=12, verbose_name='Себестоимость (₸)')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('delivery_cost', apps.common.models.MoneyField(decimal_places=2, default=0, max_digits=12, verbose_name='Доставка (всего)')),
                ('other_costs', apps.common.models.MoneyField(decimal_places=2, default=0, max_digits=12, verbose_name='Прочие затраты')),
                ('planned_price', apps.common.models.MoneyField(decimal_places=2, default=0, max_digits=12, verbose_name='Плановая цена продажи')),
                ('status', models.CharField(choices=[('in_stock', 'В наличии'), ('reserved', 'Зарезервирован'), ('sold', 'Продан')], default='in_stock', max_length=10, verbose_name='Статус')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Складской товар',
                'verbose_name_plural': 'Склад',
                'ordering': ['-id'],
            },
        ),
    ]
