# Generated by Django 5.1.15 on 2026-06-27 14:38

import apps.common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Ежемесячная')),
            ],
            options={
                'verbose_name': 'Категория расходов',
                'verbose_name_plural': 'Категории расходов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', apps.common.models.MoneyField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('expense_date', models.DateField(verbose_name='Дата расхода')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Ежемесячный')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Постоянный расход',
                'verbose_name_plural': 'Постоянные расходы',
                'ordering': ['-expense_date', '-id'],
            },
        ),
    ]
