# Generated by Django 5.1.15 on 2026-06-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('terminal', 'Терминал')], default='cash', max_length=10, verbose_name='Способ'),
        ),
        migrations.AddField(
            model_name='expense',
            name='period',
            field=models.DateField(blank=True, null=True, verbose_name='За какой месяц'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
    ]
