# Generated by Django 5.1.15 on 2026-06-27 16:36

import apps.common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_method_expense_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('planned_amount', apps.common.models.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ориентир суммы')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('terminal', 'Терминал')], default='cash', max_length=10, verbose_name='Способ (обычно)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('notes', models.TextField(blank=True, verbose_name='Заметка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring', to='expenses.expensecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ежемесячное напоминание',
                'verbose_name_plural': 'Ежемесячные напоминания',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='expenses.recurringexpense', verbose_name='Гасит напоминание'),
        ),
    ]
