# Generated by Django 5.1.15 on 2026-06-27 14:38

import apps.common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Оформил')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('taxi', 'Такси'), ('tax', 'Налог'), ('bank_fee', 'Комиссия банка'), ('other', 'Прочее')], default='other', max_length=10, verbose_name='Тип')),
                ('amount', apps.common.models.MoneyField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Доп. расход заказа',
                'verbose_name_plural': 'Доп. расходы заказа',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('cost_foreign', apps.common.models.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Себестоимость (валюта)')),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='Валюта')),
                ('cost_kzt', apps.common.models.MoneyField(decimal_places=2, max_digits=12, verbose_name='Себестоимость (₸)')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('issued_qty', models.PositiveIntegerField(default=0, verbose_name='Выдано единиц')),
                ('sale_price', apps.common.models.MoneyField(decimal_places=2, max_digits=12, verbose_name='Цена продажи (за ед.)')),
                ('delivery_price', apps.common.models.MoneyField(decimal_places=2, default=0, max_digits=12, verbose_name='Доставка (за ед.)')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('site', models.CharField(blank=True, max_length=255, verbose_name='Сайт')),
                ('track_number', models.CharField(blank=True, max_length=100, verbose_name='Трек-номер')),
                ('status', models.CharField(choices=[('ordered', 'Заказан'), ('in_transit', 'В пути'), ('received', 'Получен'), ('issued', 'Выдан')], default='ordered', max_length=12, verbose_name='Статус')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('warehouse_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='warehouse.warehouseitem', verbose_name='Складской товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Количество')),
                ('disposition', models.CharField(choices=[('restocked', 'На склад'), ('supplier_refund', 'Возврат поставщику'), ('write_off', 'Списание / брак')], max_length=16, verbose_name='Что с товаром')),
                ('refund_amount', apps.common.models.MoneyField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма возврата клиенту')),
                ('return_date', models.DateField(verbose_name='Дата возврата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.orderitem', verbose_name='Позиция заказа')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
                'ordering': ['-return_date', '-id'],
            },
        ),
    ]
