# Generated by Django 5.1.15 on 2026-06-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='Код статуса')),
                ('summary', models.CharField(max_length=255, verbose_name='Статус')),
                ('issued_qty', models.PositiveIntegerField(default=0, verbose_name='Выдано единиц')),
                ('total_qty', models.PositiveIntegerField(default=0, verbose_name='Всего единиц')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Событие статуса заказа',
                'verbose_name_plural': 'История статуса заказа',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
