# Generated by Django 5.1.15 on 2026-06-27 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Логин (снимок)')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=10, verbose_name='Действие')),
                ('app_label', models.CharField(max_length=100, verbose_name='Приложение')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('model_label', models.CharField(blank=True, max_length=150, verbose_name='Сущность')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Объект')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Изменения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Аудит изменений',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['model', 'object_id'], name='audit_audit_model_6c2be1_idx'), models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx')],
            },
        ),
    ]
