# Generated by Django 5.1.15 on 2026-06-27 14:38

import apps.common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Инвестор',
                'verbose_name_plural': 'Инвесторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('kind', models.CharField(choices=[('tax', 'На налоги'), ('monthly', 'На ежемесячные расходы'), ('other', 'Прочее')], default='other', max_length=10, verbose_name='Тип')),
                ('target_amount', apps.common.models.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цель (опц.)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Резерв',
                'verbose_name_plural': 'Резервы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Вложение'), ('return', 'Возврат инвестору')], max_length=10, verbose_name='Направление')),
                ('amount', apps.common.models.MoneyField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('terminal', 'Терминал')], default='cash', max_length=10, verbose_name='Способ')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('moved_at', models.DateField(verbose_name='Дата')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='finance.investor', verbose_name='Инвестор')),
            ],
            options={
                'verbose_name': 'Вложение / возврат инвестора',
                'verbose_name_plural': 'Вложения инвесторов',
                'ordering': ['-moved_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReserveMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('set_aside', 'Отложить'), ('release', 'Снять')], max_length=10, verbose_name='Направление')),
                ('amount', apps.common.models.MoneyField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('moved_at', models.DateField(verbose_name='Дата')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='finance.reserve', verbose_name='Резерв')),
            ],
            options={
                'verbose_name': 'Движение по резерву',
                'verbose_name_plural': 'Движения по резервам',
                'ordering': ['-moved_at', '-id'],
            },
        ),
    ]
