# Generated by Django 5.1.15 on 2026-06-27 14:38

import apps.common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='BalanceMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('direction', models.CharField(choices=[('deposit', 'Пополнение'), ('refund', 'Возврат клиенту')], max_length=10, verbose_name='Направление')),
                ('amount', apps.common.models.MoneyField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('terminal', 'Терминал')], default='cash', max_length=10, verbose_name='Способ')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('paid_at', models.DateField(verbose_name='Дата операции')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Движение по балансу',
                'verbose_name_plural': 'Движения по балансу',
                'ordering': ['-paid_at', '-id'],
            },
        ),
    ]
