# Generated by Django 5.1.15 on 2026-06-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0002_orderstatusevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancemovement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order', verbose_name='Заказ'),
        ),
    ]
